version: '3.8'

services:
  web:
    build: ./django_project
    # command: python manage.py runserver 0.0.0.0:8000
    # gunicorn
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django_project/:/usr/src/app/
    # ports:
    #   - 8000:8000 Djangoのrunserverコマンドは使用しないので、8000番ポート利用の設定をなくす
    expose:
    - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:alpine3.14
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # /var/lib/postgresql/dataにDBのデータが格納されている
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 1317:80
    depends_on:
      - web

volumes:
  postgres_data:  # ?
